# Generated by Django 4.2.10 on 2024-02-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_news_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
